# This file was generated by GoReleaser. DO NOT EDIT.
cask "gghstats" do
  version "0.7.7"

  on_macos do
    on_intel do
      sha256 "350ad33cdc34c70f2db9b96bfd47ccc6c2bc6588e2c239c99a99d0923b372fe9"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "7052d9940047e05a28969d8719e4c4e88a3aa5bcecbbbdfc4f549cc930bc70b3"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  on_linux do
    on_intel do
      sha256 "bedd010f855ce1be6d6e2fa20c1be7b207436134b232c0579eecc7612fde5539"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "3852a5c8ca2f051a34a0d714f1ca859b7d19bbe9abb4531790e7eca60cc1d876"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  name "gghstats"
  desc "Self-hosted GitHub traffic dashboard and CLI with SQLite storage"
  homepage "https://github.com/hrodrig/gghstats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gghstats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gghstats"]
    end
  end

  # No zap stanza required

end
