# This file was generated by GoReleaser. DO NOT EDIT.
cask "gghstats" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "bccf408dd7a51edd36bf67bba18cef30fdc3ffda74b39b9f064f7ace67aa937b"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "f308acd46950805520baad569740bef2070bd4ffcd50f2d9aea25d2e8e20fa2d"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bb7a81ec0fafcf8da24921f557a665de5896cf0f34b4143437adabaf355e728"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "816e831fb9991e3c972d25eb45b13e2ab042af24076299079383b4c5e1fb1c6e"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  name "gghstats"
  desc "Self-hosted GitHub traffic dashboard and CLI with SQLite storage"
  homepage "https://github.com/hrodrig/gghstats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gghstats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gghstats"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sample environment file is not bundled with the Homebrew cask.
    Generate it with `gghstats --print-sample-config > /etc/gghstats/gghstats.env`.
  EOS
end
