# This file was generated by GoReleaser. DO NOT EDIT.
cask "gghstats" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "e850985f2de18838190670a3e8f0f600dea45a3c639813f534e6973c73810ffb"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "32cd2ae64c9b4219d00110cf24ff8ffc3d4e34f0566b776932adb84dee835f2e"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e3a94af07ef571632a506cbe2b5782264fbd396a0f7f7d3431076e4d4ee61c6"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
    on_arm do
      sha256 "5394595b7408ac25902f550ef4fd3278842c1d34dd43d9215cf15e396436ecc8"
      url "https://github.com/hrodrig/gghstats/releases/download/v#{version}/gghstats_#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/gghstats/"
    end
  end

  name "gghstats"
  desc "Self-hosted GitHub traffic dashboard and CLI with SQLite storage"
  homepage "https://github.com/hrodrig/gghstats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gghstats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gghstats"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sample environment file is not bundled with the Homebrew cask.
    Generate it with `gghstats --print-sample-config > /etc/gghstats/gghstats.env`.
  EOS
end
